package asighnment3;
//help 

/**
 *
 * @author Damian
 */

import java.util.*;



public class KaitekiAirlines extends javax.swing.JFrame {
   
    

    /**
     * Creates new form KaitekiAirlines
     */
    public KaitekiAirlines() {
        initComponents();
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PassengerPanel = new javax.swing.JPanel();
        PFName = new javax.swing.JLabel();
        PLName = new javax.swing.JLabel();
        PNumber = new javax.swing.JLabel();
        FNumber = new javax.swing.JLabel();
        PFNameText = new javax.swing.JTextField();
        PLNameText = new javax.swing.JTextField();
        PNumberText = new javax.swing.JTextField();
        FNumberCombo = new javax.swing.JComboBox<>();
        PassDetailsPanel = new javax.swing.JPanel();
        BPDetails = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BPDetailsArea = new javax.swing.JTextArea();
        UpdatePassButton = new javax.swing.JButton();
        AddPassButton = new javax.swing.JButton();
        IssuePassButton = new javax.swing.JButton();
        FindPassButtton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        FindPassButton = new javax.swing.JButton();
        MapPanel = new javax.swing.JPanel();
        SeatMapLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SeatMapArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        SeatMapArea2 = new javax.swing.JTextArea();
        SpecialPanel = new javax.swing.JPanel();
        ChangeSeatCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PassengerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PassengerPanel.setEnabled(false);

        PFName.setText("Passenger First Name");

        PLName.setText("Passenger Last Name");

        PNumber.setText("Passport Number");

        FNumber.setText("Flight Number");

        PFNameText.setText("First Name");
        PFNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PFNameTextActionPerformed(evt);
            }
        });

        PLNameText.setText("Last Name");
        PLNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLNameTextActionPerformed(evt);
            }
        });

        PNumberText.setText("Passport Number");

        FNumberCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KA309", "KA409", "KA809" }));
        FNumberCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNumberComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PassengerPanelLayout = new javax.swing.GroupLayout(PassengerPanel);
        PassengerPanel.setLayout(PassengerPanelLayout);
        PassengerPanelLayout.setHorizontalGroup(
            PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addComponent(PFName)
                .addGap(18, 18, 18)
                .addComponent(PFNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PLName)
                    .addComponent(PNumber)
                    .addComponent(FNumber))
                .addGap(18, 18, 18)
                .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PLNameText)
                    .addComponent(PNumberText)
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addComponent(FNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PassengerPanelLayout.setVerticalGroup(
            PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PFName)
                    .addComponent(PFNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLName)
                    .addComponent(PLNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNumber)
                    .addComponent(PNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNumber)
                    .addComponent(FNumberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        PassDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BPDetails.setText("Boarding Pass Details");

        BPDetailsArea.setColumns(20);
        BPDetailsArea.setRows(5);
        jScrollPane3.setViewportView(BPDetailsArea);

        UpdatePassButton.setText("Update Passenger Details");

        AddPassButton.setText("Add Passenger");
        AddPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPassButtonActionPerformed(evt);
            }
        });

        IssuePassButton.setText("Issue Boarding Pass");

        FindPassButtton.setText("Find Boarding Pass");

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        FindPassButton.setText("Find Passenger");
        FindPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindPassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PassDetailsPanelLayout = new javax.swing.GroupLayout(PassDetailsPanel);
        PassDetailsPanel.setLayout(PassDetailsPanelLayout);
        PassDetailsPanelLayout.setHorizontalGroup(
            PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(BPDetails)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PassDetailsPanelLayout.createSequentialGroup()
                        .addGroup(PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PassDetailsPanelLayout.createSequentialGroup()
                                .addComponent(AddPassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(PassDetailsPanelLayout.createSequentialGroup()
                                .addComponent(IssuePassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(PassDetailsPanelLayout.createSequentialGroup()
                                .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FindPassButtton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdatePassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FindPassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PassDetailsPanelLayout.setVerticalGroup(
            PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BPDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdatePassButton)
                    .addComponent(AddPassButton))
                .addGap(36, 36, 36)
                .addGroup(PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindPassButtton)
                    .addComponent(IssuePassButton))
                .addGap(36, 36, 36)
                .addGroup(PassDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindPassButton)
                    .addComponent(ClearButton))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        MapPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SeatMapLabel.setText("Seat Map");

        SeatMapArea.setColumns(20);
        SeatMapArea.setRows(5);
        jScrollPane1.setViewportView(SeatMapArea);

        SeatMapArea2.setColumns(20);
        SeatMapArea2.setRows(5);
        jScrollPane2.setViewportView(SeatMapArea2);

        javax.swing.GroupLayout MapPanelLayout = new javax.swing.GroupLayout(MapPanel);
        MapPanel.setLayout(MapPanelLayout);
        MapPanelLayout.setHorizontalGroup(
            MapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapPanelLayout.createSequentialGroup()
                .addGroup(MapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MapPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(SeatMapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MapPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addGroup(MapPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        MapPanelLayout.setVerticalGroup(
            MapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeatMapLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        ChangeSeatCheck.setText("Change Seat");

        javax.swing.GroupLayout SpecialPanelLayout = new javax.swing.GroupLayout(SpecialPanel);
        SpecialPanel.setLayout(SpecialPanelLayout);
        SpecialPanelLayout.setHorizontalGroup(
            SpecialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChangeSeatCheck)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SpecialPanelLayout.setVerticalGroup(
            SpecialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SpecialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChangeSeatCheck)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PassDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SpecialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PassengerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PassengerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpecialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void PFNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PFNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PFNameTextActionPerformed

    private void PLNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PLNameTextActionPerformed

    private void FNumberComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNumberComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNumberComboActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
 PFNameText.setText("");
 PLNameText.setText("");
 PNumberText.setText("");
 BPDetailsArea.setText("");
 
 
    }//GEN-LAST:event_ClearButtonActionPerformed
String [] names = new String [60]; 
private ArrayList <Passenger> passengers;
    private void AddPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPassButtonActionPerformed
    int index=0; 
    if((index<60)&& !(PFNameText.getText().equals(""))&& !(PLNameText.getText().equals(""))&&(!PNumberText.getText().equals(""))){
           Passengers pass= new Passengers(); 
           pass.addPassenger(PFName,PLName,PNumber);
        }
    
     String n = "registered passenger"+ "\n";
       BPDetailsArea.setText(n);
        PFNameText.setText("");
        PLNameText.setText("");
        PNumberText.setText("");
        if(index ==60)
            BPDetailsArea.append("Registration is FULL");
    }//GEN-LAST:event_AddPassButtonActionPerformed

    private void FindPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindPassButtonActionPerformed
       
    }//GEN-LAST:event_FindPassButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KaitekiAirlines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(() -> {
            new KaitekiAirlines().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPassButton;
    private javax.swing.JLabel BPDetails;
    private javax.swing.JTextArea BPDetailsArea;
    private javax.swing.JCheckBox ChangeSeatCheck;
    private javax.swing.JButton ClearButton;
    private javax.swing.JLabel FNumber;
    private javax.swing.JComboBox<String> FNumberCombo;
    private javax.swing.JButton FindPassButton;
    private javax.swing.JButton FindPassButtton;
    private javax.swing.JButton IssuePassButton;
    private javax.swing.JPanel MapPanel;
    private javax.swing.JLabel PFName;
    private javax.swing.JTextField PFNameText;
    private javax.swing.JLabel PLName;
    private javax.swing.JTextField PLNameText;
    private javax.swing.JLabel PNumber;
    private javax.swing.JTextField PNumberText;
    private javax.swing.JPanel PassDetailsPanel;
    private javax.swing.JPanel PassengerPanel;
    private javax.swing.JTextArea SeatMapArea;
    private javax.swing.JTextArea SeatMapArea2;
    private javax.swing.JLabel SeatMapLabel;
    private javax.swing.JPanel SpecialPanel;
    private javax.swing.JButton UpdatePassButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
